-- DROP TABLES if they already exist (for development)
DROP TABLE IF EXISTS team_batting_stats CASCADE;
DROP TABLE IF EXISTS team_pitching_stats CASCADE;
DROP TABLE IF EXISTS team_fielding_stats CASCADE;
DROP TABLE IF EXISTS standings CASCADE;
DROP TABLE IF EXISTS schedule_and_record CASCADE;
DROP TABLE IF EXISTS player_batting_stats CASCADE;
DROP TABLE IF EXISTS player_pitching_stats CASCADE;
DROP TABLE IF EXISTS amateur_draft CASCADE;
DROP TABLE IF EXISTS team_game_logs_batting CASCADE;
DROP TABLE IF EXISTS team_game_logs_pitching CASCADE;

-- ======================================================
-- Table for yearly team batting statistics
-- (All numeric columns from the fetch output are mapped as INTEGER for int64 and REAL for float64.
--  TEXT is used for object columns.)
-- ======================================================
DROP TABLE IF EXISTS team_batting;
CREATE TABLE team_batting (
  "teamIDfg"      INTEGER,
  "Season"        INTEGER,
  "Team"          TEXT,
  "Age"           INTEGER,
  "G"             INTEGER,
  "AB"            INTEGER,
  "PA"            INTEGER,
  "H"             INTEGER,
  "1B"            INTEGER,
  "2B"            INTEGER,
  "3B"            INTEGER,
  "HR"            INTEGER,
  "R"             INTEGER,
  "RBI"           INTEGER,
  "BB"            INTEGER,
  "IBB"           INTEGER,
  "SO"            INTEGER,
  "HBP"           INTEGER,
  "SF"            INTEGER,
  "SH"            INTEGER,
  "GDP"           INTEGER,
  "SB"            INTEGER,
  "CS"            INTEGER,
  "AVG"           DOUBLE PRECISION,
  "GB"            INTEGER,
  "FB"            INTEGER,
  "LD"            INTEGER,
  "IFFB"          INTEGER,
  "Pitches"       INTEGER,
  "Balls"         INTEGER,
  "Strikes"       INTEGER,
  "IFH"           INTEGER,
  "BU"            INTEGER,
  "BUH"           INTEGER,
  "BB%"           DOUBLE PRECISION,
  "K%"            DOUBLE PRECISION,
  "BB/K"          DOUBLE PRECISION,
  "OBP"           DOUBLE PRECISION,
  "SLG"           DOUBLE PRECISION,
  "OPS"           DOUBLE PRECISION,
  "ISO"           DOUBLE PRECISION,
  "BABIP"         DOUBLE PRECISION,
  "GB/FB"         DOUBLE PRECISION,
  "LD%"           DOUBLE PRECISION,
  "GB%"           DOUBLE PRECISION,
  "FB%"           DOUBLE PRECISION,
  "IFFB%"         DOUBLE PRECISION,
  "HR/FB"         DOUBLE PRECISION,
  "IFH%"          DOUBLE PRECISION,
  "BUH%"          DOUBLE PRECISION,
  "wOBA"          DOUBLE PRECISION,
  "wRAA"          DOUBLE PRECISION,
  "wRC"           INTEGER,
  "Bat"           DOUBLE PRECISION,
  "Fld"           DOUBLE PRECISION,
  "Rep"           DOUBLE PRECISION,
  "Pos"           DOUBLE PRECISION,
  "RAR"           DOUBLE PRECISION,
  "WAR"           DOUBLE PRECISION,
  "Dol"           TEXT,
  "Spd"           DOUBLE PRECISION,
  "wRC+"          INTEGER,
  "WPA"           DOUBLE PRECISION,
  "-WPA"          DOUBLE PRECISION,
  "+WPA"          DOUBLE PRECISION,
  "RE24"          DOUBLE PRECISION,
  "REW"           DOUBLE PRECISION,
  "pLI"           DOUBLE PRECISION,
  "phLI"          DOUBLE PRECISION,
  "PH"            INTEGER,
  "WPA/LI"        DOUBLE PRECISION,
  "Clutch"        DOUBLE PRECISION,
  "FB% (Pitch)"   DOUBLE PRECISION,
  "FBv"           DOUBLE PRECISION,
  "SL%"           DOUBLE PRECISION,
  "SLv"           DOUBLE PRECISION,
  "CT%"           DOUBLE PRECISION,
  "CTv"           DOUBLE PRECISION,
  "CB%"           DOUBLE PRECISION,
  "CBv"           DOUBLE PRECISION,
  "CH%"           DOUBLE PRECISION,
  "CHv"           DOUBLE PRECISION,
  "SF%"           DOUBLE PRECISION,
  "SFv"           DOUBLE PRECISION,
  "KN%"           DOUBLE PRECISION,
  "KNv"           DOUBLE PRECISION,
  "XX%"           DOUBLE PRECISION,
  "PO%"           DOUBLE PRECISION,
  "wFB"           DOUBLE PRECISION,
  "wSL"           DOUBLE PRECISION,
  "wCT"           DOUBLE PRECISION,
  "wCB"           DOUBLE PRECISION,
  "wCH"           DOUBLE PRECISION,
  "wSF"           DOUBLE PRECISION,
  "wKN"           DOUBLE PRECISION,
  "wFB/C"         DOUBLE PRECISION,
  "wSL/C"         DOUBLE PRECISION,
  "wCT/C"         DOUBLE PRECISION,
  "wCB/C"         DOUBLE PRECISION,
  "wCH/C"         DOUBLE PRECISION,
  "wSF/C"         DOUBLE PRECISION,
  "wKN/C"         DOUBLE PRECISION,
  "O-Swing%"      DOUBLE PRECISION,
  "Z-Swing%"      DOUBLE PRECISION,
  "Swing%"        DOUBLE PRECISION,
  "O-Contact%"    DOUBLE PRECISION,
  "Z-Contact%"    DOUBLE PRECISION,
  "Contact%"      DOUBLE PRECISION,
  "Zone%"         DOUBLE PRECISION,
  "F-Strike%"     DOUBLE PRECISION,
  "SwStr%"        DOUBLE PRECISION,
  "BsR"           DOUBLE PRECISION,
  "FA% (sc)"      DOUBLE PRECISION,
  "FT% (sc)"      DOUBLE PRECISION,
  "FC% (sc)"      DOUBLE PRECISION,
  "FS% (sc)"      DOUBLE PRECISION,
  "FO% (sc)"      DOUBLE PRECISION,
  "SI% (sc)"      DOUBLE PRECISION,
  "SL% (sc)"      DOUBLE PRECISION,
  "CU% (sc)"      DOUBLE PRECISION,
  "KC% (sc)"      DOUBLE PRECISION,
  "EP% (sc)"      DOUBLE PRECISION,
  "CH% (sc)"      DOUBLE PRECISION,
  "SC% (sc)"      DOUBLE PRECISION,
  "KN% (sc)"      DOUBLE PRECISION,
  "UN% (sc)"      DOUBLE PRECISION,
  "vFA (sc)"      DOUBLE PRECISION,
  "vFT (sc)"      DOUBLE PRECISION,
  "vFC (sc)"      DOUBLE PRECISION,
  "vFS (sc)"      DOUBLE PRECISION,
  "vFO (sc)"      DOUBLE PRECISION,
  "vSI (sc)"      DOUBLE PRECISION,
  "vSL (sc)"      DOUBLE PRECISION,
  "vCU (sc)"      DOUBLE PRECISION,
  "vKC (sc)"      DOUBLE PRECISION,
  "vEP (sc)"      DOUBLE PRECISION,
  "vCH (sc)"      DOUBLE PRECISION,
  "vSC (sc)"      DOUBLE PRECISION,
  "vKN (sc)"      DOUBLE PRECISION,
  "FA-X (sc)"     DOUBLE PRECISION,
  "FT-X (sc)"     DOUBLE PRECISION,
  "FC-X (sc)"     DOUBLE PRECISION,
  "FS-X (sc)"     DOUBLE PRECISION,
  "FO-X (sc)"     DOUBLE PRECISION,
  "SI-X (sc)"     DOUBLE PRECISION,
  "SL-X (sc)"     DOUBLE PRECISION,
  "CU-X (sc)"     DOUBLE PRECISION,
  "KC-X (sc)"     DOUBLE PRECISION,
  "EP-X (sc)"     DOUBLE PRECISION,
  "CH-X (sc)"     DOUBLE PRECISION,
  "SC-X (sc)"     DOUBLE PRECISION,
  "KN-X (sc)"     DOUBLE PRECISION,
  "FA-Z (sc)"     DOUBLE PRECISION,
  "FT-Z (sc)"     DOUBLE PRECISION,
  "FC-Z (sc)"     DOUBLE PRECISION,
  "FS-Z (sc)"     DOUBLE PRECISION,
  "FO-Z (sc)"     DOUBLE PRECISION,
  "SI-Z (sc)"     DOUBLE PRECISION,
  "SL-Z (sc)"     DOUBLE PRECISION,
  "CU-Z (sc)"     DOUBLE PRECISION,
  "KC-Z (sc)"     DOUBLE PRECISION,
  "EP-Z (sc)"     DOUBLE PRECISION,
  "CH-Z (sc)"     DOUBLE PRECISION,
  "SC-Z (sc)"     DOUBLE PRECISION,
  "KN-Z (sc)"     DOUBLE PRECISION
);

-- ======================================================
-- Table for yearly team pitching statistics
-- (Use the same mapping: int64 -> INTEGER, float64 -> REAL, object -> TEXT.
--  Be sure to quote column names that are not standard identifiers.)
-- ======================================================
DROP TABLE IF EXISTS team_pitching;
CREATE TABLE team_pitching (
  "teamIDfg"      INTEGER,
  "Season"        INTEGER,
  "Team"          TEXT,
  "Age"           INTEGER,
  "W"             INTEGER,
  "L"             INTEGER,
  "ERA"           DOUBLE PRECISION,
  "G"             INTEGER,
  "GS"            INTEGER,
  "CG"            INTEGER,
  "ShO"           INTEGER,
  "SV"            INTEGER,
  "BS"            INTEGER,
  "IP"            DOUBLE PRECISION,
  "TBF"           INTEGER,
  "H"             INTEGER,
  "R"             INTEGER,
  "ER"            INTEGER,
  "HR"            INTEGER,
  "BB"            INTEGER,
  "IBB"           INTEGER,
  "HBP"           INTEGER,
  "WP"            INTEGER,
  "BK"            INTEGER,
  "SO"            INTEGER,
  "GB"            INTEGER,
  "FB"            INTEGER,
  "LD"            INTEGER,
  "IFFB"          INTEGER,
  "Balls"         INTEGER,
  "Strikes"       INTEGER,
  "Pitches"       INTEGER,
  "RS"            INTEGER,
  "IFH"           INTEGER,
  "BU"            INTEGER,
  "BUH"           INTEGER,
  "K/9"           DOUBLE PRECISION,
  "BB/9"          DOUBLE PRECISION,
  "K/BB"          DOUBLE PRECISION,
  "H/9"           DOUBLE PRECISION,
  "HR/9"          DOUBLE PRECISION,
  "AVG"           DOUBLE PRECISION,
  "WHIP"          DOUBLE PRECISION,
  "BABIP"         DOUBLE PRECISION,
  "LOB%"          DOUBLE PRECISION,
  "FIP"           DOUBLE PRECISION,
  "GB/FB"         DOUBLE PRECISION,
  "LD%"           DOUBLE PRECISION,
  "GB%"           DOUBLE PRECISION,
  "FB%"           DOUBLE PRECISION,
  "IFFB%"         DOUBLE PRECISION,
  "HR/FB"         DOUBLE PRECISION,
  "IFH%"          DOUBLE PRECISION,
  "BUH%"          DOUBLE PRECISION,
  "Starting"      DOUBLE PRECISION,
  "Start-IP"      DOUBLE PRECISION,
  "Relieving"     DOUBLE PRECISION,
  "Relief-IP"     DOUBLE PRECISION,
  "RAR"           DOUBLE PRECISION,
  "WAR"           DOUBLE PRECISION,
  "Dollars"       TEXT,
  "tERA"          DOUBLE PRECISION,
  "xFIP"          DOUBLE PRECISION,
  "WPA"           DOUBLE PRECISION,
  "-WPA"          DOUBLE PRECISION,
  "+WPA"          DOUBLE PRECISION,
  "RE24"          DOUBLE PRECISION,
  "REW"           DOUBLE PRECISION,
  "pLI"           DOUBLE PRECISION,
  "inLI"          DOUBLE PRECISION,
  "gmLI"          DOUBLE PRECISION,
  "exLI"          DOUBLE PRECISION,
  "Pulls"         INTEGER,
  "WPA/LI"        DOUBLE PRECISION,
  "Clutch"        DOUBLE PRECISION,
  "FB% 2"         DOUBLE PRECISION,
  "FBv"           DOUBLE PRECISION,
  "SL%"           DOUBLE PRECISION,
  "SLv"           DOUBLE PRECISION,
  "CT%"           DOUBLE PRECISION,
  "CTv"           DOUBLE PRECISION,
  "CB%"           DOUBLE PRECISION,
  "CBv"           DOUBLE PRECISION,
  "CH%"           DOUBLE PRECISION,
  "CHv"           DOUBLE PRECISION,
  "SF%"           DOUBLE PRECISION,
  "SFv"           DOUBLE PRECISION,
  "KN%"           DOUBLE PRECISION,
  "KNv"           DOUBLE PRECISION,
  "XX%"           DOUBLE PRECISION,
  "PO%"           DOUBLE PRECISION,
  "wFB"           DOUBLE PRECISION,
  "wSL"           DOUBLE PRECISION,
  "wCT"           DOUBLE PRECISION,
  "wCB"           DOUBLE PRECISION,
  "wCH"           DOUBLE PRECISION,
  "wSF"           DOUBLE PRECISION,
  "wKN"           DOUBLE PRECISION,
  "wFB/C"         DOUBLE PRECISION,
  "wSL/C"         DOUBLE PRECISION,
  "wCT/C"         DOUBLE PRECISION,
  "wCB/C"         DOUBLE PRECISION,
  "wCH/C"         DOUBLE PRECISION,
  "wSF/C"         DOUBLE PRECISION,
  "wKN/C"         DOUBLE PRECISION,
  "O-Swing%"      DOUBLE PRECISION,
  "Z-Swing%"      DOUBLE PRECISION,
  "Swing%"        DOUBLE PRECISION,
  "O-Contact%"    DOUBLE PRECISION,
  "Z-Contact%"    DOUBLE PRECISION,
  "Contact%"      DOUBLE PRECISION,
  "Zone%"         DOUBLE PRECISION,
  "F-Strike%"     DOUBLE PRECISION,
  "SwStr%"        DOUBLE PRECISION,
  "HLD"           INTEGER,
  "SD"            INTEGER,
  "MD"            INTEGER,
  "ERA-"          INTEGER,
  "FIP-"          INTEGER,
  "xFIP-"         INTEGER,
  "K%"            DOUBLE PRECISION,
  "BB%"           DOUBLE PRECISION,
  "SIERA"         DOUBLE PRECISION,
  "RS/9"          DOUBLE PRECISION,
  "E-F"           DOUBLE PRECISION,
  "FA% (sc)"      DOUBLE PRECISION,
  "FT% (sc)"      DOUBLE PRECISION,
  "FC% (sc)"      DOUBLE PRECISION,
  "FS% (sc)"      DOUBLE PRECISION,
  "FO% (sc)"      DOUBLE PRECISION,
  "SI% (sc)"      DOUBLE PRECISION,
  "SL% (sc)"      DOUBLE PRECISION,
  "CU% (sc)"      DOUBLE PRECISION,
  "KC% (sc)"      DOUBLE PRECISION,
  "EP% (sc)"      DOUBLE PRECISION,
  "CH% (sc)"      DOUBLE PRECISION,
  "SC% (sc)"      DOUBLE PRECISION,
  "KN% (sc)"      DOUBLE PRECISION,
  "UN% (sc)"      DOUBLE PRECISION,
  "vFA (sc)"      DOUBLE PRECISION,
  "vFT (sc)"      DOUBLE PRECISION,
  "vFC (sc)"      DOUBLE PRECISION,
  "vFS (sc)"      DOUBLE PRECISION,
  "vFO (sc)"      DOUBLE PRECISION,
  "vSI (sc)"      DOUBLE PRECISION,
  "vSL (sc)"      DOUBLE PRECISION,
  "vCU (sc)"      DOUBLE PRECISION,
  "vKC (sc)"      DOUBLE PRECISION,
  "vEP (sc)"      DOUBLE PRECISION,
  "vCH (sc)"      DOUBLE PRECISION,
  "vSC (sc)"      DOUBLE PRECISION,
  "vKN (sc)"      DOUBLE PRECISION,
  "FA-X (sc)"     DOUBLE PRECISION,
  "FT-X (sc)"     DOUBLE PRECISION,
  "FC-X (sc)"     DOUBLE PRECISION,
  "FS-X (sc)"     DOUBLE PRECISION,
  "FO-X (sc)"     DOUBLE PRECISION,
  "SI-X (sc)"     DOUBLE PRECISION,
  "SL-X (sc)"     DOUBLE PRECISION,
  "CU-X (sc)"     DOUBLE PRECISION,
  "KC-X (sc)"     DOUBLE PRECISION,
  "EP-X (sc)"     DOUBLE PRECISION,
  "CH-X (sc)"     DOUBLE PRECISION,
  "SC-X (sc)"     DOUBLE PRECISION,
  "KN-X (sc)"     DOUBLE PRECISION,
  "FA-Z (sc)"     DOUBLE PRECISION,
  "FT-Z (sc)"     DOUBLE PRECISION,
  "FC-Z (sc)"     DOUBLE PRECISION,
  "FS-Z (sc)"     DOUBLE PRECISION,
  "FO-Z (sc)"     DOUBLE PRECISION,
  "SI-Z (sc)"     DOUBLE PRECISION,
  "SL-Z (sc)"     DOUBLE PRECISION,
  "CU-Z (sc)"     DOUBLE PRECISION,
  "KC-Z (sc)"     DOUBLE PRECISION,
  "EP-Z (sc)"     DOUBLE PRECISION,
  "CH-Z (sc)"     DOUBLE PRECISION,
  "SC-Z (sc)"     DOUBLE PRECISION,
  "KN-Z (sc)"     DOUBLE PRECISION
);


-- ======================================================
-- Table for team fielding (yearly)
-- (Use similar mapping. For brevity, only a sample subset is shown.)
-- ======================================================
DROP TABLE IF EXISTS team_fielding;
CREATE TABLE team_fielding (
  "teamIDfg"      INTEGER,
  "Season"        INTEGER,
  "Team"          TEXT,
  "G"             INTEGER,
  "GS"            INTEGER,
  "Inn"           DOUBLE PRECISION,
  "PO"            INTEGER,
  "A"             INTEGER,
  "E"             INTEGER,
  "FE"            INTEGER,
  "TE"            INTEGER,
  "DP"            INTEGER,
  "DPS"           INTEGER,
  "DPT"           INTEGER,
  "DPF"           INTEGER,
  "Scp"           INTEGER,
  "SB"            INTEGER,
  "CS"            INTEGER,
  "PB"            INTEGER,
  "WP"            INTEGER,
  "FP"            DOUBLE PRECISION,
  "TZ"            DOUBLE PRECISION,
  "rSB"           INTEGER,
  "rGDP"          INTEGER,
  "rARM"          INTEGER,
  "rGFP"          INTEGER,
  "rPM"           INTEGER,
  "DRS"           INTEGER,
  "BIZ"           INTEGER,
  "Plays"         INTEGER,
  "RZR"           DOUBLE PRECISION,
  "OOZ"           INTEGER,
  "TZL"           DOUBLE PRECISION,
  "FSR"           DOUBLE PRECISION,
  "ARM"           DOUBLE PRECISION,
  "DPR"           DOUBLE PRECISION,
  "RngR"          DOUBLE PRECISION,
  "ErrR"          DOUBLE PRECISION,
  "UZR"           DOUBLE PRECISION,
  "UZR/150"       DOUBLE PRECISION,
  "CPP"           DOUBLE PRECISION,
  "RPP"           DOUBLE PRECISION,
  "Def"           DOUBLE PRECISION,
  "0%"            DOUBLE PRECISION,
  "# 0%"          DOUBLE PRECISION,
  "1-10%"         DOUBLE PRECISION,
  "# 1-10%"       DOUBLE PRECISION,
  "10-40%"        DOUBLE PRECISION,
  "# 10-40%"      DOUBLE PRECISION,
  "40-60%"        DOUBLE PRECISION,
  "# 40-60%"      DOUBLE PRECISION,
  "60-90%"        DOUBLE PRECISION,
  "# 60-90%"      DOUBLE PRECISION,
  "90-100%"       DOUBLE PRECISION,
  "# 90-100%"     DOUBLE PRECISION,
  "rSZ"           INTEGER,
  "rCERA"         INTEGER,
  "rTS"           INTEGER,
  "FRM"           DOUBLE PRECISION,
  "OAA"           INTEGER,
  "Range"         INTEGER
);


-- ======================================================
-- Table for standings (yearly league standings)
-- ======================================================
DROP TABLE IF EXISTS standings;
CREATE TABLE standings (
    "Season" INTEGER,
    "Tm" TEXT,
    "W" INTEGER,
    "L" INTEGER,
    "W-L%" DOUBLE PRECISION,
    "GB" TEXT
);


-- ======================================================
-- Table for schedule and record (game-by-game schedule/results for a team)
-- ======================================================
DROP TABLE IF EXISTS schedule_and_record;
CREATE TABLE schedule_and_record (
  "Date"              TEXT,
  "Tm"                TEXT,
  "Home_Away"         TEXT,
  "Opp"               TEXT,
  "W/L"              TEXT,
  "R"                DOUBLE PRECISION,
  "RA"               DOUBLE PRECISION,
  "Inn"              DOUBLE PRECISION,
  "W-L"              TEXT,
  "Rank"             DOUBLE PRECISION,
  "GB"               TEXT,
  "Win"              TEXT,
  "Loss"             TEXT,
  "Save"             TEXT,
  "Time"             TEXT,
  "D/N"              TEXT,
  "Attendance"       DOUBLE PRECISION,
  "cLI"              TEXT,
  "Streak"           INTEGER,
  "Orig. Scheduled"  TEXT
);


-- ======================================================
-- Table for yearly individual batting statistics
-- (Columns based on the batting_stats fetch output.)
-- ======================================================
DROP TABLE IF EXISTS player_batting_stats;
CREATE TABLE player_batting_stats (
  "IDfg"           INTEGER,
  "Season"         INTEGER,
  "Name"           TEXT,
  "Team"           TEXT,
  "Age"            INTEGER,
  "G"              INTEGER,
  "AB"             INTEGER,
  "PA"             INTEGER,
  "H"              INTEGER,
  "1B"             INTEGER,
  "2B"             INTEGER,
  "3B"             INTEGER,
  "HR"             INTEGER,
  "R"              INTEGER,
  "RBI"            INTEGER,
  "BB"             INTEGER,
  "IBB"            INTEGER,
  "SO"             INTEGER,
  "HBP"            INTEGER,
  "SF"             INTEGER,
  "SH"             INTEGER,
  "GDP"            INTEGER,
  "SB"             INTEGER,
  "CS"             INTEGER,
  "AVG"            DOUBLE PRECISION,
  "GB"             INTEGER,
  "FB"             INTEGER,
  "LD"             INTEGER,
  "IFFB"           INTEGER,
  "Pitches"        INTEGER,
  "Balls"          INTEGER,
  "Strikes"        INTEGER,
  "IFH"            INTEGER,
  "BU"             INTEGER,
  "BUH"            INTEGER,
  "BB%"            DOUBLE PRECISION,
  "K%"             DOUBLE PRECISION,
  "BB/K"           DOUBLE PRECISION,
  "OBP"            DOUBLE PRECISION,
  "SLG"            DOUBLE PRECISION,
  "OPS"            DOUBLE PRECISION,
  "ISO"            DOUBLE PRECISION,
  "BABIP"          DOUBLE PRECISION,
  "GB/FB"          DOUBLE PRECISION,
  "LD%"            DOUBLE PRECISION,
  "GB%"            DOUBLE PRECISION,
  "FB%"            DOUBLE PRECISION,
  "IFFB%"          DOUBLE PRECISION,
  "HR/FB"          DOUBLE PRECISION,
  "IFH%"           DOUBLE PRECISION,
  "BUH%"           DOUBLE PRECISION,
  "wOBA"           DOUBLE PRECISION,
  "wRAA"           DOUBLE PRECISION,
  "wRC"            INTEGER,
  "Bat"            DOUBLE PRECISION,
  "Fld"            DOUBLE PRECISION,
  "Rep"            DOUBLE PRECISION,
  "Pos"            DOUBLE PRECISION,
  "RAR"            DOUBLE PRECISION,
  "WAR"            DOUBLE PRECISION,
  "Dol"            TEXT,
  "Spd"            DOUBLE PRECISION,
  "wRC+"           INTEGER,
  "WPA"            DOUBLE PRECISION,
  "-WPA"           DOUBLE PRECISION,
  "+WPA"           DOUBLE PRECISION,
  "RE24"           DOUBLE PRECISION,
  "REW"            DOUBLE PRECISION,
  "pLI"            DOUBLE PRECISION,
  "phLI"           DOUBLE PRECISION,
  "PH"             INTEGER,
  "WPA/LI"         DOUBLE PRECISION,
  "Clutch"         DOUBLE PRECISION,
  "FB% (Pitch)"    DOUBLE PRECISION,
  "FBv"            DOUBLE PRECISION,
  "SL%"            DOUBLE PRECISION,
  "SLv"            DOUBLE PRECISION,
  "CT%"            DOUBLE PRECISION,
  "CTv"            DOUBLE PRECISION,
  "CB%"            DOUBLE PRECISION,
  "CBv"            DOUBLE PRECISION,
  "CH%"            DOUBLE PRECISION,
  "CHv"            DOUBLE PRECISION,
  "SF%"            DOUBLE PRECISION,
  "SFv"            DOUBLE PRECISION,
  "KN%"            DOUBLE PRECISION,
  "KNv"            DOUBLE PRECISION,
  "XX%"            DOUBLE PRECISION,
  "PO%"            DOUBLE PRECISION,
  "wFB"            DOUBLE PRECISION,
  "wSL"            DOUBLE PRECISION,
  "wCT"            DOUBLE PRECISION,
  "wCB"            DOUBLE PRECISION,
  "wCH"            DOUBLE PRECISION,
  "wSF"            DOUBLE PRECISION,
  "wKN"            DOUBLE PRECISION,
  "wFB/C"          DOUBLE PRECISION,
  "wSL/C"          DOUBLE PRECISION,
  "wCT/C"          DOUBLE PRECISION,
  "wCB/C"          DOUBLE PRECISION,
  "wCH/C"          DOUBLE PRECISION,
  "wSF/C"          DOUBLE PRECISION,
  "wKN/C"          DOUBLE PRECISION,
  "O-Swing%"       DOUBLE PRECISION,
  "Z-Swing%"       DOUBLE PRECISION,
  "Swing%"         DOUBLE PRECISION,
  "O-Contact%"     DOUBLE PRECISION,
  "Z-Contact%"     DOUBLE PRECISION,
  "Contact%"       DOUBLE PRECISION,
  "Zone%"          DOUBLE PRECISION,
  "F-Strike%"      DOUBLE PRECISION,
  "SwStr%"         DOUBLE PRECISION,
  "BsR"            DOUBLE PRECISION,
  "FA% (sc)"       DOUBLE PRECISION,
  "FT% (sc)"       DOUBLE PRECISION,
  "FC% (sc)"       DOUBLE PRECISION,
  "FS% (sc)"       DOUBLE PRECISION,
  "FO% (sc)"       DOUBLE PRECISION,
  "SI% (sc)"       DOUBLE PRECISION,
  "SL% (sc)"       DOUBLE PRECISION,
  "CU% (sc)"       DOUBLE PRECISION,
  "KC% (sc)"       DOUBLE PRECISION,
  "EP% (sc)"       DOUBLE PRECISION,
  "CH% (sc)"       DOUBLE PRECISION,
  "SC% (sc)"       DOUBLE PRECISION,
  "KN% (sc)"       DOUBLE PRECISION,
  "UN% (sc)"       DOUBLE PRECISION,
  "vFA (sc)"       DOUBLE PRECISION,
  "vFT (sc)"       DOUBLE PRECISION,
  "vFC (sc)"       DOUBLE PRECISION,
  "vFS (sc)"       DOUBLE PRECISION,
  "vFO (sc)"       DOUBLE PRECISION,
  "vSI (sc)"       DOUBLE PRECISION,
  "vSL (sc)"       DOUBLE PRECISION,
  "vCU (sc)"       DOUBLE PRECISION,
  "vKC (sc)"       DOUBLE PRECISION,
  "vEP (sc)"       DOUBLE PRECISION,
  "vCH (sc)"       DOUBLE PRECISION,
  "vSC (sc)"       DOUBLE PRECISION,
  "vKN (sc)"       DOUBLE PRECISION,
  "FA-X (sc)"      DOUBLE PRECISION,
  "FT-X (sc)"      DOUBLE PRECISION,
  "FC-X (sc)"      DOUBLE PRECISION,
  "FS-X (sc)"      DOUBLE PRECISION,
  "FO-X (sc)"      DOUBLE PRECISION,
  "SI-X (sc)"      DOUBLE PRECISION,
  "SL-X (sc)"      DOUBLE PRECISION,
  "CU-X (sc)"      DOUBLE PRECISION,
  "KC-X (sc)"      DOUBLE PRECISION,
  "EP-X (sc)"      DOUBLE PRECISION,
  "CH-X (sc)"      DOUBLE PRECISION,
  "SC-X (sc)"      DOUBLE PRECISION,
  "KN-X (sc)"      DOUBLE PRECISION,
  "FA-Z (sc)"      DOUBLE PRECISION,
  "FT-Z (sc)"      DOUBLE PRECISION,
  "FC-Z (sc)"      DOUBLE PRECISION,
  "FS-Z (sc)"      DOUBLE PRECISION,
  "FO-Z (sc)"      DOUBLE PRECISION,
  "SI-Z (sc)"      DOUBLE PRECISION,
  "SL-Z (sc)"      DOUBLE PRECISION,
  "CU-Z (sc)"      DOUBLE PRECISION,
  "KC-Z (sc)"      DOUBLE PRECISION,
  "EP-Z (sc)"      DOUBLE PRECISION,
  "CH-Z (sc)"      DOUBLE PRECISION,
  "SC-Z (sc)"      DOUBLE PRECISION,
  "KN-Z (sc)"      DOUBLE PRECISION,
  "wCH (sc)"       DOUBLE PRECISION,
  "wCS (sc)"       DOUBLE PRECISION,
  "wCU (sc)"       DOUBLE PRECISION,
  "wFA (sc)"       DOUBLE PRECISION,
  "wFC (sc)"       DOUBLE PRECISION,
  "wFS (sc)"       DOUBLE PRECISION,
  "wKN (sc)"       DOUBLE PRECISION,
  "wSB (sc)"       DOUBLE PRECISION,
  "wSI (sc)"       DOUBLE PRECISION,
  "wSL (sc)"       DOUBLE PRECISION,
  "wXX (sc)"       DOUBLE PRECISION,
  "wCH/C (sc)"     DOUBLE PRECISION,
  "wCS/C (sc)"     DOUBLE PRECISION,
  "wCU/C (sc)"     DOUBLE PRECISION,
  "wFA/C (sc)"     DOUBLE PRECISION,
  "wFC/C (sc)"     DOUBLE PRECISION,
  "wFS/C (sc)"     DOUBLE PRECISION,
  "wKN/C (sc)"     DOUBLE PRECISION,
  "O-Swing% (sc)"  DOUBLE PRECISION,
  "Z-Swing% (sc)"  DOUBLE PRECISION,
  "Swing% (sc)"    DOUBLE PRECISION,
  "O-Contact% (sc)" DOUBLE PRECISION,
  "Z-Contact% (sc)" DOUBLE PRECISION,
  "Contact% (sc)"  DOUBLE PRECISION,
  "Zone% (sc)"     DOUBLE PRECISION,
  "Pace"           DOUBLE PRECISION,
  "Def"            DOUBLE PRECISION,
  "wSB"            DOUBLE PRECISION,
  "UBR"            DOUBLE PRECISION,
  "Age Rng"        TEXT,
  "Off"            DOUBLE PRECISION,
  "Lg"             DOUBLE PRECISION,
  "wGDP"           DOUBLE PRECISION,
  "Pull%"          DOUBLE PRECISION,
  "Cent%"          DOUBLE PRECISION,
  "Oppo%"          DOUBLE PRECISION,
  "Soft%"          DOUBLE PRECISION,
  "Med%"           DOUBLE PRECISION,
  "Hard%"          DOUBLE PRECISION,
  "TTO%"          DOUBLE PRECISION,
  "CH% (pi)"       DOUBLE PRECISION,
  "CS% (pi)"       DOUBLE PRECISION,
  "CU% (pi)"       DOUBLE PRECISION,
  "FA% (pi)"       DOUBLE PRECISION,
  "FC% (pi)"       DOUBLE PRECISION,
  "FS% (pi)"       DOUBLE PRECISION,
  "KN% (pi)"       DOUBLE PRECISION,
  "SB% (pi)"       DOUBLE PRECISION,
  "SI% (pi)"       DOUBLE PRECISION,
  "SL% (pi)"       DOUBLE PRECISION,
  "XX% (pi)"       DOUBLE PRECISION,
  "vCH (pi)"       DOUBLE PRECISION,
  "vCS (pi)"       DOUBLE PRECISION,
  "vCU (pi)"       DOUBLE PRECISION,
  "vFA (pi)"       DOUBLE PRECISION,
  "vFC (pi)"       DOUBLE PRECISION,
  "vFS (pi)"       DOUBLE PRECISION,
  "vKN (pi)"       DOUBLE PRECISION,
  "vSB (pi)"       DOUBLE PRECISION,
  "vSI (pi)"       DOUBLE PRECISION,
  "vSL (pi)"       DOUBLE PRECISION,
  "vXX (pi)"       DOUBLE PRECISION,
  "CH-X (pi)"      DOUBLE PRECISION,
  "CS-X (pi)"      DOUBLE PRECISION,
  "CU-X (pi)"      DOUBLE PRECISION,
  "FA-X (pi)"      DOUBLE PRECISION,
  "FC-X (pi)"      DOUBLE PRECISION,
  "FS-X (pi)"      DOUBLE PRECISION,
  "KN-X (pi)"      DOUBLE PRECISION,
  "SB-X (pi)"      DOUBLE PRECISION,
  "SI-X (pi)"      DOUBLE PRECISION,
  "SL-X (pi)"      DOUBLE PRECISION,
  "XX-X (pi)"      DOUBLE PRECISION,
  "CH-Z (pi)"      DOUBLE PRECISION,
  "CS-Z (pi)"      DOUBLE PRECISION,
  "CU-Z (pi)"      DOUBLE PRECISION,
  "FA-Z (pi)"      DOUBLE PRECISION,
  "FC-Z (pi)"      DOUBLE PRECISION,
  "FS-Z (pi)"      DOUBLE PRECISION,
  "KN-Z (pi)"      DOUBLE PRECISION,
  "SB-Z (pi)"      DOUBLE PRECISION,
  "SI-Z (pi)"      DOUBLE PRECISION,
  "SL-Z (pi)"      DOUBLE PRECISION,
  "XX-Z (pi)"      DOUBLE PRECISION,
  "wCH (pi)"       DOUBLE PRECISION,
  "wCS (pi)"       DOUBLE PRECISION,
  "wCU (pi)"       DOUBLE PRECISION,
  "wFA (pi)"       DOUBLE PRECISION,
  "wFC (pi)"       DOUBLE PRECISION,
  "wFS (pi)"       DOUBLE PRECISION,
  "wKN (pi)"       DOUBLE PRECISION,
  "wSB (pi)"       DOUBLE PRECISION,
  "wSI (pi)"       DOUBLE PRECISION,
  "wSL (pi)"       DOUBLE PRECISION,
  "wXX (pi)"       DOUBLE PRECISION,
  "wCH/C (pi)"     DOUBLE PRECISION,
  "wCS/C (pi)"     DOUBLE PRECISION,
  "wCU/C (pi)"     DOUBLE PRECISION,
  "wFA/C (pi)"     DOUBLE PRECISION,
  "wFC/C (pi)"     DOUBLE PRECISION,
  "wFS/C (pi)"     DOUBLE PRECISION,
  "wKN/C (pi)"     DOUBLE PRECISION,
  "O-Swing% (pi)"  DOUBLE PRECISION,
  "Z-Swing% (pi)"  DOUBLE PRECISION,
  "Swing% (pi)"    DOUBLE PRECISION,
  "O-Contact% (pi)" DOUBLE PRECISION,
  "Z-Contact% (pi)" DOUBLE PRECISION,
  "Contact% (pi)"  DOUBLE PRECISION,
  "Zone% (pi)"     DOUBLE PRECISION,
  "Pace (pi)"      DOUBLE PRECISION,
  "FRM"            DOUBLE PRECISION,
  "AVG+"           INTEGER,
  "BB%+"           INTEGER,
  "K%+"            INTEGER,
  "OBP+"           INTEGER,
  "SLG+"           INTEGER,
  "ISO+"           INTEGER,
  "BABIP+"         INTEGER,
  "LD+%"           DOUBLE PRECISION,
  "GB%+"           INTEGER,
  "FB%+"           INTEGER,
  "HR/FB%+"        INTEGER,
  "Pull%+"         INTEGER,
  "Cent%+"         INTEGER,
  "Oppo%+"         INTEGER,
  "Soft%+"         INTEGER,
  "Med%+"          INTEGER,
  "Hard%+"         INTEGER,
  "EV"             DOUBLE PRECISION,
  "LA"             DOUBLE PRECISION,
  "Barrels"        INTEGER,
  "Barrel%"        DOUBLE PRECISION,
  "maxEV"          DOUBLE PRECISION,
  "HardHit"        INTEGER,
  "HardHit%"       DOUBLE PRECISION,
  "Events"         INTEGER,
  "CStr%"         DOUBLE PRECISION,
  "CSW%"          DOUBLE PRECISION,
  "xBA"           DOUBLE PRECISION,
  "xSLG"          DOUBLE PRECISION,
  "xwOBA"         DOUBLE PRECISION,
  "L-WAR"         DOUBLE PRECISION
);


-- ======================================================
-- Table for yearly individual pitching statistics
-- (Define columns similarly based on the pitching_stats output.)
-- For brevity, only a representative subset is shown here.
-- ======================================================
DROP TABLE IF EXISTS player_pitching_stats;
CREATE TABLE player_pitching_stats (
  "IDfg"            INTEGER,
  "Season"          INTEGER,
  "Name"            TEXT,
  "Team"            TEXT,
  "Age"             INTEGER,
  "W"               INTEGER,
  "L"               INTEGER,
  "WAR"             DOUBLE PRECISION,
  "ERA"             DOUBLE PRECISION,
  "G"               INTEGER,
  "GS"              INTEGER,
  "CG"              INTEGER,
  "ShO"             INTEGER,
  "SV"              INTEGER,
  "BS"              INTEGER,
  "IP"              DOUBLE PRECISION,
  "TBF"             INTEGER,
  "H"               INTEGER,
  "R"               INTEGER,
  "ER"              INTEGER,
  "HR"              INTEGER,
  "BB"              INTEGER,
  "IBB"             INTEGER,
  "HBP"             INTEGER,
  "WP"              INTEGER,
  "BK"              INTEGER,
  "SO"              INTEGER,
  "GB"              INTEGER,
  "FB"              INTEGER,
  "LD"              INTEGER,
  "IFFB"            INTEGER,
  "Balls"           INTEGER,
  "Strikes"         INTEGER,
  "Pitches"         INTEGER,
  "RS"              INTEGER,
  "IFH"             INTEGER,
  "BU"              INTEGER,
  "BUH"             INTEGER,
  "K/9"             DOUBLE PRECISION,
  "BB/9"            DOUBLE PRECISION,
  "K/BB"            DOUBLE PRECISION,
  "H/9"             DOUBLE PRECISION,
  "HR/9"            DOUBLE PRECISION,
  "AVG"             DOUBLE PRECISION,
  "WHIP"            DOUBLE PRECISION,
  "BABIP"           DOUBLE PRECISION,
  "LOB%"            DOUBLE PRECISION,
  "FIP"             DOUBLE PRECISION,
  "GB/FB"           DOUBLE PRECISION,
  "LD%"             DOUBLE PRECISION,
  "GB%"             DOUBLE PRECISION,
  "FB%"             DOUBLE PRECISION,
  "IFFB%"           DOUBLE PRECISION,
  "HR/FB"           DOUBLE PRECISION,
  "IFH%"            DOUBLE PRECISION,
  "BUH%"            DOUBLE PRECISION,
  "Starting"        DOUBLE PRECISION,
  "Start-IP"        DOUBLE PRECISION,
  "Relieving"       DOUBLE PRECISION,
  "Relief-IP"       DOUBLE PRECISION,
  "RAR"             DOUBLE PRECISION,
  "Dollars"         TEXT,
  "tERA"            DOUBLE PRECISION,
  "xFIP"            DOUBLE PRECISION,
  "WPA"             DOUBLE PRECISION,
  "-WPA"            DOUBLE PRECISION,
  "+WPA"            DOUBLE PRECISION,
  "RE24"            DOUBLE PRECISION,
  "REW"             DOUBLE PRECISION,
  "pLI"             DOUBLE PRECISION,
  "inLI"            DOUBLE PRECISION,
  "gmLI"            DOUBLE PRECISION,
  "exLI"            DOUBLE PRECISION,
  "Pulls"           INTEGER,
  "WPA/LI"          DOUBLE PRECISION,
  "Clutch"          DOUBLE PRECISION,
  "FB% 2"           DOUBLE PRECISION,
  "FBv"             DOUBLE PRECISION,
  "SL%"             DOUBLE PRECISION,
  "SLv"             DOUBLE PRECISION,
  "CT%"             DOUBLE PRECISION,
  "CTv"             DOUBLE PRECISION,
  "CB%"             DOUBLE PRECISION,
  "CBv"             DOUBLE PRECISION,
  "CH%"             DOUBLE PRECISION,
  "CHv"             DOUBLE PRECISION,
  "SF%"             DOUBLE PRECISION,
  "SFv"             DOUBLE PRECISION,
  "KN%"             DOUBLE PRECISION,
  "KNv"             DOUBLE PRECISION,
  "XX%"             DOUBLE PRECISION,
  "PO%"             DOUBLE PRECISION,
  "wFB"             DOUBLE PRECISION,
  "wSL"             DOUBLE PRECISION,
  "wCT"             DOUBLE PRECISION,
  "wCB"             DOUBLE PRECISION,
  "wCH"             DOUBLE PRECISION,
  "wSF"             DOUBLE PRECISION,
  "wKN"             DOUBLE PRECISION,
  "wFB/C"           DOUBLE PRECISION,
  "wSL/C"           DOUBLE PRECISION,
  "wCT/C"           DOUBLE PRECISION,
  "wCB/C"           DOUBLE PRECISION,
  "wCH/C"           DOUBLE PRECISION,
  "wSF/C"           DOUBLE PRECISION,
  "wKN/C"           DOUBLE PRECISION,
  "O-Swing%"        DOUBLE PRECISION,
  "Z-Swing%"        DOUBLE PRECISION,
  "Swing%"          DOUBLE PRECISION,
  "O-Contact%"      DOUBLE PRECISION,
  "Z-Contact%"      DOUBLE PRECISION,
  "Contact%"        DOUBLE PRECISION,
  "Zone%"           DOUBLE PRECISION,
  "F-Strike%"       DOUBLE PRECISION,
  "SwStr%"          DOUBLE PRECISION,
  "HLD"             INTEGER,
  "SD"              INTEGER,
  "MD"              INTEGER,
  "ERA-"            INTEGER,
  "FIP-"            INTEGER,
  "xFIP-"           INTEGER,
  "K%"              DOUBLE PRECISION,
  "BB%"             DOUBLE PRECISION,
  "SIERA"           DOUBLE PRECISION,
  "RS/9"            DOUBLE PRECISION,
  "E-F"             DOUBLE PRECISION,
  "FA% (sc)"        DOUBLE PRECISION,
  "FT% (sc)"        DOUBLE PRECISION,
  "FC% (sc)"        DOUBLE PRECISION,
  "FS% (sc)"        DOUBLE PRECISION,
  "FO% (sc)"        DOUBLE PRECISION,
  "SI% (sc)"        DOUBLE PRECISION,
  "SL% (sc)"        DOUBLE PRECISION,
  "CU% (sc)"        DOUBLE PRECISION,
  "KC% (sc)"        DOUBLE PRECISION,
  "EP% (sc)"        DOUBLE PRECISION,
  "CH% (sc)"        DOUBLE PRECISION,
  "SC% (sc)"        DOUBLE PRECISION,
  "KN% (sc)"        DOUBLE PRECISION,
  "UN% (sc)"        DOUBLE PRECISION,
  "vFA (sc)"        DOUBLE PRECISION,
  "vFT (sc)"        DOUBLE PRECISION,
  "vFC (sc)"        DOUBLE PRECISION,
  "vFS (sc)"        DOUBLE PRECISION,
  "vFO (sc)"        DOUBLE PRECISION,
  "vSI (sc)"        DOUBLE PRECISION,
  "vSL (sc)"        DOUBLE PRECISION,
  "vCU (sc)"        DOUBLE PRECISION,
  "vKC (sc)"        DOUBLE PRECISION,
  "vEP (sc)"        DOUBLE PRECISION,
  "vCH (sc)"        DOUBLE PRECISION,
  "vSC (sc)"        DOUBLE PRECISION,
  "vKN (sc)"        DOUBLE PRECISION,
  "FA-X (sc)"       DOUBLE PRECISION,
  "FT-X (sc)"       DOUBLE PRECISION,
  "FC-X (sc)"       DOUBLE PRECISION,
  "FS-X (sc)"       DOUBLE PRECISION,
  "FO-X (sc)"       DOUBLE PRECISION,
  "SI-X (sc)"       DOUBLE PRECISION,
  "SL-X (sc)"       DOUBLE PRECISION,
  "CU-X (sc)"       DOUBLE PRECISION,
  "KC-X (sc)"       DOUBLE PRECISION,
  "EP-X (sc)"       DOUBLE PRECISION,
  "CH-X (sc)"       DOUBLE PRECISION,
  "SC-X (sc)"       DOUBLE PRECISION,
  "KN-X (sc)"       DOUBLE PRECISION,
  "FA-Z (sc)"       DOUBLE PRECISION,
  "FT-Z (sc)"       DOUBLE PRECISION,
  "FC-Z (sc)"       DOUBLE PRECISION,
  "FS-Z (sc)"       DOUBLE PRECISION,
  "FO-Z (sc)"       DOUBLE PRECISION,
  "SI-Z (sc)"       DOUBLE PRECISION,
  "SL-Z (sc)"       DOUBLE PRECISION,
  "CU-Z (sc)"       DOUBLE PRECISION,
  "KC-Z (sc)"       DOUBLE PRECISION,
  "EP-Z (sc)"       DOUBLE PRECISION,
  "CH-Z (sc)"       DOUBLE PRECISION,
  "SC-Z (sc)"       DOUBLE PRECISION,
  "KN-Z (sc)"       DOUBLE PRECISION,
  "wCH (sc)"        DOUBLE PRECISION,
  "wCS (sc)"        DOUBLE PRECISION,
  "wCU (sc)"        DOUBLE PRECISION,
  "wFA (sc)"        DOUBLE PRECISION,
  "wFC (sc)"        DOUBLE PRECISION,
  "wFS (sc)"        DOUBLE PRECISION,
  "wKN (sc)"        DOUBLE PRECISION,
  "wSB (sc)"        DOUBLE PRECISION,
  "wSI (sc)"        DOUBLE PRECISION,
  "wSL (sc)"        DOUBLE PRECISION,
  "wXX (sc)"        DOUBLE PRECISION,
  "wCH/C (sc)"      DOUBLE PRECISION,
  "wCS/C (sc)"      DOUBLE PRECISION,
  "wCU/C (sc)"      DOUBLE PRECISION,
  "wFA/C (sc)"      DOUBLE PRECISION,
  "wFC/C (sc)"      DOUBLE PRECISION,
  "wFS/C (sc)"      DOUBLE PRECISION,
  "wKN/C (sc)"      DOUBLE PRECISION,
  "O-Swing% (sc)"   DOUBLE PRECISION,
  "Z-Swing% (sc)"   DOUBLE PRECISION,
  "Swing% (sc)"     DOUBLE PRECISION,
  "O-Contact% (sc)" DOUBLE PRECISION,
  "Z-Contact% (sc)" DOUBLE PRECISION,
  "Contact% (sc)"   DOUBLE PRECISION,
  "Zone% (sc)"      DOUBLE PRECISION,
  "Pace (sc)"       DOUBLE PRECISION,
  "FRM"             DOUBLE PRECISION,
  "K/9+"            INTEGER,
  "BB/9+"           INTEGER,
  "K/BB+"           INTEGER,
  "H/9+"            INTEGER,
  "HR/9+"           INTEGER,
  "AVG+"            INTEGER,
  "WHIP+"           INTEGER,
  "BABIP+"          INTEGER,
  "LOB%+"           INTEGER,
  "K%+"             INTEGER,
  "BB%+"            INTEGER,
  "LD%+"            INTEGER,
  "GB%+"            INTEGER,
  "FB%+"            INTEGER,
  "HR/FB%+"         INTEGER,
  "Pull%+"          INTEGER,
  "Cent%+"          INTEGER,
  "Oppo%+"          INTEGER,
  "Soft%+"          INTEGER,
  "Med%+"           INTEGER,
  "Hard%+"          INTEGER,
  "EV"              DOUBLE PRECISION,
  "LA"              DOUBLE PRECISION,
  "Barrels"         INTEGER,
  "Barrel%"         DOUBLE PRECISION,
  "maxEV"           DOUBLE PRECISION,
  "HardHit"         INTEGER,
  "HardHit%"        DOUBLE PRECISION,
  "Events"          INTEGER,
  "CStr%"          DOUBLE PRECISION,
  "CSW%"           DOUBLE PRECISION,
  "xBA"            DOUBLE PRECISION,
  "xSLG"           DOUBLE PRECISION,
  "xwOBA"          DOUBLE PRECISION,
  "L-WAR"          DOUBLE PRECISION
);


-- ======================================================
-- Table for amateur draft (team-based)
-- ======================================================
DROP TABLE IF EXISTS amateur_draft_by_team;
CREATE TABLE amateur_draft_by_team (
  "OvPck"          INTEGER,
  "Tm"             TEXT,
  "Signed"         TEXT,
  "Bonus"          TEXT,
  "Name"           TEXT,
  "Pos"            TEXT,
  "WAR"            DOUBLE PRECISION,
  "G"              DOUBLE PRECISION,
  "AB"             DOUBLE PRECISION,
  "HR"             DOUBLE PRECISION,
  "BA"             DOUBLE PRECISION,
  "OPS"            DOUBLE PRECISION,
  "G.1"            DOUBLE PRECISION,
  "W"              DOUBLE PRECISION,
  "L"              DOUBLE PRECISION,
  "ERA"            DOUBLE PRECISION,
  "WHIP"           DOUBLE PRECISION,
  "SV"             DOUBLE PRECISION,
  "Type"           TEXT,
  "Drafted Out of" TEXT
);


-- ======================================================
-- Table for team game logs (batting logs)
-- ======================================================
DROP TABLE IF EXISTS team_game_logs_batting;
CREATE TABLE team_game_logs_batting (
  "Game"       INTEGER,
  "Date"       TEXT,
  "Home"       BOOLEAN,
  "Opp"        TEXT,
  "Rslt"       TEXT,
  "PA"         INTEGER,
  "AB"         INTEGER,
  "R"          INTEGER,
  "H"          INTEGER,
  "2B"         INTEGER,
  "3B"         INTEGER,
  "HR"         INTEGER,
  "RBI"        INTEGER,
  "BB"         INTEGER,
  "IBB"        INTEGER,
  "SO"         INTEGER,
  "HBP"        INTEGER,
  "SH"         INTEGER,
  "SF"         INTEGER,
  "ROE"        INTEGER,
  "GDP"        INTEGER,
  "SB"         INTEGER,
  "CS"         INTEGER,
  "BA"         DOUBLE PRECISION,
  "OBP"        DOUBLE PRECISION,
  "SLG"        DOUBLE PRECISION,
  "OPS"        DOUBLE PRECISION,
  "LOB"        INTEGER,
  "NumPlayers" INTEGER,
  "Thr"        TEXT,
  "OppStart"   TEXT
);


-- ======================================================
-- Table for team game logs (pitching logs)
-- ======================================================
DROP TABLE IF EXISTS team_game_logs_pitching;
CREATE TABLE team_game_logs_pitching (
  "Game"         INTEGER,
  "Date"         TEXT,
  "Home"         BOOLEAN,
  "Opp"          TEXT,
  "Rslt"         TEXT,
  "IP"           DOUBLE PRECISION,
  "H"            INTEGER,
  "R"            INTEGER,
  "ER"           INTEGER,
  "UER"          INTEGER,
  "BB"           INTEGER,
  "SO"           INTEGER,
  "HR"           INTEGER,
  "HBP"          INTEGER,
  "ERA"          DOUBLE PRECISION,
  "BF"           INTEGER,
  "Pit"          INTEGER,
  "Str"          INTEGER,
  "IR"           DOUBLE PRECISION,
  "IS"           DOUBLE PRECISION,
  "SB"           INTEGER,
  "CS"           INTEGER,
  "AB"           INTEGER,
  "2B"           INTEGER,
  "3B"           INTEGER,
  "IBB"          INTEGER,
  "SH"           INTEGER,
  "SF"           INTEGER,
  "ROE"          INTEGER,
  "GDP"          INTEGER,
  "NumPlayers"   INTEGER,
  "Umpire"       TEXT,
  "PitchersUsed" TEXT
);
