-- DROP TABLES if they already exist (for development)
DROP TABLE IF EXISTS team_batting CASCADE;
DROP TABLE IF EXISTS team_pitching CASCADE;
DROP TABLE IF EXISTS team_fielding CASCADE;
DROP TABLE IF EXISTS standings CASCADE;
DROP TABLE IF EXISTS schedule_and_record CASCADE;
DROP TABLE IF EXISTS batting_stats CASCADE;
DROP TABLE IF EXISTS pitching_stats CASCADE;
DROP TABLE IF EXISTS amateur_draft_by_team CASCADE;
DROP TABLE IF EXISTS team_game_logs_batting CASCADE;
DROP TABLE IF EXISTS team_game_logs_pitching CASCADE;

-- ======================================================
-- Table for yearly team batting statistics
-- (All numeric columns from the fetch output are mapped as INTEGER for int64 and REAL for float64.
--  TEXT is used for object columns.)
-- ======================================================
CREATE TABLE team_batting (
    teamIDfg         INTEGER,
    Season           INTEGER,
    Team             TEXT,
    Age              INTEGER,
    G                INTEGER,
    AB               INTEGER,
    PA               INTEGER,
    H                INTEGER,
    "1B"             INTEGER,
    "2B"             INTEGER,
    "3B"             INTEGER,
    HR               INTEGER,
    R                INTEGER,
    RBI              INTEGER,
    BB               INTEGER,
    IBB              INTEGER,
    SO               INTEGER,
    HBP              INTEGER,
    SF               INTEGER,
    SH               INTEGER,
    GDP              INTEGER,
    SB               INTEGER,
    CS               INTEGER,
    AVG              REAL,
    GB               INTEGER,
    FB               INTEGER,
    LD               INTEGER,
    IFFB             INTEGER,
    Pitches          INTEGER,
    Balls            INTEGER,
    Strikes          INTEGER,
    IFH              INTEGER,
    BU               INTEGER,
    BUH              INTEGER,
    "BB%"           REAL,
    "K%"            REAL,
    "BB/K"          REAL,
    OBP              REAL,
    SLG              REAL,
    OPS              REAL,
    ISO              REAL,
    BABIP            REAL,
    "GB/FB"         REAL,
    "LD%"           REAL,
    "GB%"           REAL,
    "FB%"           REAL,
    "IFFB%"         REAL,
    "HR/FB"         REAL,
    "IFH%"          REAL,
    "BUH%"          REAL,
    wOBA             REAL,
    wRAA             REAL,
    wRC              INTEGER,
    Bat              REAL,
    Fld              REAL,
    Rep              REAL,
    Pos              REAL,
    RAR              REAL,
    WAR              REAL,
    Dol              TEXT,
    Spd              REAL,
    "wRC+"          INTEGER,
    WPA              REAL,
    "-WPA"          REAL,
    "+WPA"          REAL,
    RE24             REAL,
    REW              REAL,
    pLI              REAL,
    phLI             REAL,
    PH               INTEGER,
    "WPA/LI"        REAL,
    Clutch           REAL,
    "FB% (Pitch)"    REAL,
    FBv              REAL,
    "SL%"           REAL,
    SLv              REAL,
    "CT%"           REAL,
    CTv              REAL,
    "CB%"           REAL,
    CBv              REAL,
    "CH%"           REAL,
    CHv              REAL,
    "SF%"           REAL,
    SFv              REAL,
    "KN%"           REAL,
    KNv              REAL,
    "XX%"           REAL,
    "PO%"           REAL,
    wFB              REAL,
    wSL              REAL,
    wCT              REAL,
    wCB              REAL,
    wCH              REAL,
    wSF              REAL,
    wKN              REAL,
    "wFB/C"         REAL,
    "wSL/C"         REAL,
    "wCT/C"         REAL,
    "wCB/C"         REAL,
    "wCH/C"         REAL,
    "wSF/C"         REAL,
    "wKN/C"         REAL,
    "O-Swing%"      REAL,
    "Z-Swing%"      REAL,
    Swing            REAL,
    "O-Contact%"    REAL,
    "Z-Contact%"    REAL,
    Contact          REAL,
    Zone             REAL,
    "F-Strike%"     REAL,
    "SwStr%"        REAL,
    BsR              REAL,
    "FA% (sc)"      REAL,
    "FT% (sc)"      REAL,
    "FC% (sc)"      REAL,
    "FS% (sc)"      REAL,
    "FO% (sc)"      REAL,
    "SI% (sc)"      REAL,
    "SL% (sc)"      REAL,
    "CU% (sc)"      REAL,
    "KC% (sc)"      REAL,
    "EP% (sc)"      REAL,
    "CH% (sc)"      REAL,
    "SC% (sc)"      REAL,
    "KN% (sc)"      REAL,
    "UN% (sc)"      REAL,
    "vFA (sc)"      REAL,
    "vFT (sc)"      REAL,
    "vFC (sc)"      REAL,
    "vFS (sc)"      REAL,
    "vFO (sc)"      REAL,
    "vSI (sc)"      REAL,
    "vSL (sc)"      REAL,
    "vCU (sc)"      REAL,
    "vKC (sc)"      REAL,
    "vEP (sc)"      REAL,
    "vCH (sc)"      REAL,
    "vSC (sc)"      REAL,
    "vKN (sc)"      REAL,
    "FA-X (sc)"     REAL,
    "FT-X (sc)"     REAL,
    "FC-X (sc)"     REAL,
    "FS-X (sc)"     REAL,
    "FO-X (sc)"     REAL,
    "SI-X (sc)"     REAL,
    "SL-X (sc)"     REAL,
    "CU-X (sc)"     REAL,
    "KC-X (sc)"     REAL,
    "EP-X (sc)"     REAL,
    "CH-X (sc)"     REAL,
    "SC-X (sc)"     REAL,
    "KN-X (sc)"     REAL,
    "FA-Z (sc)"     REAL,
    "FT-Z (sc)"     REAL,
    "FC-Z (sc)"     REAL,
    "FS-Z (sc)"     REAL,
    "FO-Z (sc)"     REAL,
    "SI-Z (sc)"     REAL,
    "SL-Z (sc)"     REAL,
    "CU-Z (sc)"     REAL,
    "KC-Z (sc)"     REAL,
    "EP-Z (sc)"     REAL,
    "CH-Z (sc)"     REAL,
    "SC-Z (sc)"     REAL,
    "KN-Z (sc)"     REAL
);

-- ======================================================
-- Table for yearly team pitching statistics
-- (Use the same mapping: int64 -> INTEGER, float64 -> REAL, object -> TEXT.
--  Be sure to quote column names that are not standard identifiers.)
-- ======================================================
DROP TABLE IF EXISTS team_pitching;
CREATE TABLE team_pitching (
    teamIDfg    INTEGER,
    Season      INTEGER,
    Team        TEXT,
    Age         INTEGER,
    W           INTEGER,
    L           INTEGER,
    ERA         REAL,
    G           INTEGER,
    GS          INTEGER,
    CG          INTEGER,
    ShO         INTEGER,
    SV          INTEGER,
    BS          INTEGER,
    IP          REAL,
    TBF         INTEGER,
    H           INTEGER,
    R           INTEGER,
    ER          INTEGER,
    HR          INTEGER,
    BB          INTEGER,
    IBB         INTEGER,
    HBP         INTEGER,
    WP          INTEGER,
    BK          INTEGER,
    SO          INTEGER,
    GB          INTEGER,
    FB          INTEGER,
    LD          INTEGER,
    IFFB        INTEGER,
    Balls       INTEGER,
    Strikes     INTEGER,
    Pitches     INTEGER,
    RS          INTEGER,
    IFH         INTEGER,
    BU          INTEGER,
    BUH         INTEGER,
    "K/9"       REAL,
    "BB/9"      REAL,
    "K/BB"      REAL,
    "H/9"       REAL,
    "HR/9"      REAL,
    AVG         REAL,
    WHIP        REAL,
    BABIP       REAL,
    "LOB%"      REAL,
    FIP         REAL,
    "GB/FB"     REAL,
    "LD%"       REAL,
    "GB%"       REAL,
    "FB%"       REAL,
    "IFFB%"     REAL,
    "HR/FB"     REAL,
    "IFH%"      REAL,
    "BUH%"      REAL,
    Starting    REAL,
    "Start-IP"  REAL,
    Relieving   REAL,
    "Relief-IP" REAL,
    RAR         REAL,
    WAR         REAL,
    Dollars     TEXT,
    tERA        REAL,
    xFIP        REAL,
    WPA         REAL,
    "-WPA"      REAL,
    "+WPA"      REAL,
    RE24        REAL,
    REW         REAL,
    pLI         REAL,
    inLI        REAL,
    gmLI        REAL,
    exLI        REAL,
    Pulls       INTEGER,
    "WPA/LI"    REAL,
    Clutch      REAL,
    "FB% 2"     REAL,
    FBv         REAL,
    "SL%"       REAL,
    SLv         REAL,
    "CT%"       REAL,
    CTv         REAL,
    "CB%"       REAL,
    CBv         REAL,
    "CH%"       REAL,
    CHv         REAL,
    "SF%"       REAL,
    SFv         REAL,
    "KN%"       REAL,
    KNv         REAL,
    "XX%"       REAL,
    "PO%"       REAL,
    wFB         REAL,
    wSL         REAL,
    wCT         REAL,
    wCB         REAL,
    wCH         REAL,
    wSF         REAL,
    wKN         REAL,
    "wFB/C"     REAL,
    "wSL/C"     REAL,
    "wCT/C"     REAL,
    "wCB/C"     REAL,
    "wCH/C"     REAL,
    "wSF/C"     REAL,
    "wKN/C"     REAL
    -- (Add any remaining columns as needed based on your fetch output.)
);

-- ======================================================
-- Table for team fielding (yearly)
-- (Use similar mapping. For brevity, only a sample subset is shown.)
-- ======================================================
DROP TABLE IF EXISTS team_fielding;
CREATE TABLE team_fielding (
    teamIDfg  INTEGER,
    Season    INTEGER,
    Team      TEXT,
    -- Add additional columns as defined by the fielding fetch output:
    G         INTEGER,
    GS        INTEGER,
    Inn       REAL,
    PO        INTEGER,
    A         INTEGER,
    E         INTEGER,
    FE        INTEGER,
    TE        INTEGER,
    DP        INTEGER,
    DPS       INTEGER,
    DPT       INTEGER,
    DPF       INTEGER,
    Scp       INTEGER,
    SB        INTEGER,
    CS        INTEGER,
    PB        INTEGER,
    WP        INTEGER,
    FP        REAL,
    TZ        REAL,
    rSB       INTEGER,
    rGDP      INTEGER,
    rARM      INTEGER,
    rGFP      INTEGER,
    rPM       INTEGER,
    DRS       INTEGER,
    BIZ       INTEGER,
    Plays     INTEGER,
    RZR       REAL,
    OOZ       INTEGER,
    TZL       REAL,
    FSR       REAL,
    ARM       REAL,
    DPR       REAL,
    RngR      REAL,
    ErrR      REAL,
    UZR       REAL,
    "UZR/150" REAL,
    CPP       REAL,
    RPP       REAL,
    Def       REAL,
    "0%"      REAL,
    "# 0%"    REAL,
    "1-10%"   REAL,
    "# 1-10%" REAL,
    "10-40%"  REAL,
    "# 10-40%" REAL,
    "40-60%"  REAL,
    "# 40-60%" REAL,
    "60-90%"  REAL,
    "# 60-90%" REAL,
    "90-100%" REAL,
    "# 90-100%" REAL,
    rSZ       INTEGER,
    rCERA     INTEGER,
    rTS       INTEGER,
    FRM       REAL,
    OAA       INTEGER,
    Range     INTEGER
);

-- ======================================================
-- Table for standings (yearly league standings)
-- ======================================================
DROP TABLE IF EXISTS standings;
CREATE TABLE standings (
    Season  INTEGER,
    data    JSONB  -- Use JSONB if the standings fetch is wide or may vary
);

-- ======================================================
-- Table for schedule and record (game-by-game schedule/results for a team)
-- ======================================================
DROP TABLE IF EXISTS schedule_and_record;
CREATE TABLE schedule_and_record (
    Season    INTEGER,
    Team      TEXT,
    Date      TEXT,
    Tm        TEXT,
    Home_Away TEXT,
    Opp       TEXT,
    "W/L"   TEXT,
    R         REAL,
    RA        REAL,
    Inn       REAL,
    "W-L"   TEXT,
    Rank      REAL,
    GB        TEXT,
    Win       TEXT,
    Loss      TEXT,
    Save      TEXT,
    Time      TEXT,
    "D/N"   TEXT,
    Attendance REAL,
    cLI       TEXT,
    Streak    INTEGER,
    "Orig. Scheduled" TEXT
);

-- ======================================================
-- Table for yearly individual batting statistics
-- (Columns based on the batting_stats fetch output.)
-- ======================================================
DROP TABLE IF EXISTS batting_stats;
CREATE TABLE batting_stats (
    IDfg       INTEGER,
    Season     INTEGER,
    Name       TEXT,
    Team       TEXT,
    Age        INTEGER,
    G          INTEGER,
    AB         INTEGER,
    PA         INTEGER,
    H          INTEGER,
    "1B"       INTEGER,
    "2B"       INTEGER,
    "3B"       INTEGER,
    HR         INTEGER,
    R          INTEGER,
    RBI        INTEGER,
    BB         INTEGER,
    IBB        INTEGER,
    SO         INTEGER,
    HBP        INTEGER,
    SF         INTEGER,
    SH         INTEGER,
    GDP        INTEGER,
    SB         INTEGER,
    CS         INTEGER,
    AVG        REAL,
    GB         INTEGER,
    FB         INTEGER,
    LD         INTEGER,
    IFFB       INTEGER,
    Pitches    INTEGER,
    Balls      INTEGER,
    Strikes    INTEGER,
    IFH        INTEGER,
    BU         INTEGER,
    BUH        INTEGER,
    "BB%"      REAL,
    "K%"       REAL,
    "BB/K"     REAL,
    OBP        REAL,
    SLG        REAL,
    OPS        REAL,
    ISO        REAL,
    BABIP      REAL,
    "GB/FB"    REAL,
    "LD%"      REAL,
    "GB%"      REAL,
    "FB%"      REAL,
    "IFFB%"    REAL,
    "HR/FB"    REAL,
    "IFH%"     REAL,
    "BUH%"     REAL,
    wOBA       REAL,
    wRAA       REAL,
    wRC        INTEGER,
    Bat        REAL,
    Fld        REAL,
    Rep        REAL,
    Pos        REAL,
    RAR        REAL,
    WAR        REAL,
    Dol        TEXT,
    Spd        REAL,
    "wRC+"     INTEGER,
    WPA        REAL,
    "-WPA"     REAL,
    "+WPA"     REAL,
    RE24       REAL,
    REW        REAL,
    pLI        REAL,
    phLI       REAL,
    PH         INTEGER,
    "WPA/LI"   REAL,
    Clutch     REAL,
    "FB% (Pitch)" REAL,
    FBv        REAL,
    "SL%"      REAL,
    SLv        REAL,
    "CT%"      REAL,
    CTv        REAL,
    "CB%"      REAL,
    CBv        REAL,
    "CH%"      REAL,
    CHv        REAL,
    "SF%"      REAL,
    SFv        REAL,
    "KN%"      REAL,
    KNv        REAL,
    "XX%"      REAL,
    "PO%"      REAL,
    wFB        REAL,
    wSL        REAL,
    wCT        REAL,
    wCB        REAL,
    wCH        REAL,
    wSF        REAL,
    wKN        REAL,
    "wFB/C"    REAL,
    "wSL/C"    REAL,
    "wCT/C"    REAL,
    "wCB/C"    REAL,
    "wCH/C"    REAL,
    "wSF/C"    REAL,
    "wKN/C"    REAL,
    "O-Swing%" REAL,
    "Z-Swing%" REAL,
    Swing      REAL,
    "O-Contact%" REAL,
    "Z-Contact%" REAL,
    Contact    REAL,
    Zone       REAL,
    "F-Strike%" REAL,
    "SwStr%"   REAL,
    BsR        REAL,
    "FA% (sc)" REAL,
    "FT% (sc)" REAL,
    "FC% (sc)" REAL,
    "FS% (sc)" REAL,
    "FO% (sc)" REAL,
    "SI% (sc)" REAL,
    "SL% (sc)" REAL,
    "CU% (sc)" REAL,
    "KC% (sc)" REAL,
    "EP% (sc)" REAL,
    "CH% (sc)" REAL,
    "SC% (sc)" REAL,
    "KN% (sc)" REAL,
    "UN% (sc)" REAL,
    "vFA (sc)" REAL,
    "vFT (sc)" REAL,
    "vFC (sc)" REAL,
    "vFS (sc)" REAL,
    "vFO (sc)" REAL,
    "vSI (sc)" REAL,
    "vSL (sc)" REAL,
    "vCU (sc)" REAL,
    "vKC (sc)" REAL,
    "vEP (sc)" REAL,
    "vCH (sc)" REAL,
    "vSC (sc)" REAL,
    "vKN (sc)" REAL,
    "FA-X (sc)" REAL,
    "FT-X (sc)" REAL,
    "FC-X (sc)" REAL,
    "FS-X (sc)" REAL,
    "FO-X (sc)" REAL,
    "SI-X (sc)" REAL,
    "SL-X (sc)" REAL,
    "CU-X (sc)" REAL,
    "KC-X (sc)" REAL,
    "EP-X (sc)" REAL,
    "CH-X (sc)" REAL,
    "SC-X (sc)" REAL,
    "KN-X (sc)" REAL,
    "FA-Z (sc)" REAL,
    "FT-Z (sc)" REAL,
    "FC-Z (sc)" REAL,
    "FS-Z (sc)" REAL,
    "FO-Z (sc)" REAL,
    "SI-Z (sc)" REAL,
    "SL-Z (sc)" REAL,
    "CU-Z (sc)" REAL,
    "KC-Z (sc)" REAL,
    "EP-Z (sc)" REAL,
    "CH-Z (sc)" REAL,
    "SC-Z (sc)" REAL,
    "KN-Z (sc)" REAL
);

-- ======================================================
-- Table for yearly individual pitching statistics
-- (Define columns similarly based on the pitching_stats output.)
-- For brevity, only a representative subset is shown here.
-- ======================================================
DROP TABLE IF EXISTS pitching_stats;
CREATE TABLE pitching_stats (
    teamIDfg   INTEGER,
    Season     INTEGER,
    Team       TEXT,
    Age        INTEGER,
    W          INTEGER,
    L          INTEGER,
    ERA        REAL,
    G          INTEGER,
    GS         INTEGER,
    CG         INTEGER,
    ShO        INTEGER,
    SV         INTEGER,
    BS         INTEGER,
    IP         REAL,
    TBF        INTEGER,
    H          INTEGER,
    R          INTEGER,
    ER         INTEGER,
    HR         INTEGER,
    BB         INTEGER,
    IBB        INTEGER,
    HBP        INTEGER,
    WP         INTEGER,
    BK         INTEGER,
    SO         INTEGER,
    GB         INTEGER,
    FB         INTEGER,
    LD         INTEGER,
    IFFB       INTEGER,
    Balls      INTEGER,
    Strikes    INTEGER,
    Pitches    INTEGER,
    RS         INTEGER,
    IFH        INTEGER,
    BU         INTEGER,
    BUH        INTEGER,
    "K/9"      REAL,
    "BB/9"     REAL,
    "K/BB"     REAL,
    "H/9"      REAL,
    "HR/9"     REAL,
    AVG        REAL,
    WHIP       REAL,
    BABIP      REAL,
    "LOB%"     REAL,
    FIP        REAL,
    "GB/FB"    REAL,
    "LD%"      REAL,
    "GB%"      REAL,
    "FB%"      REAL,
    "IFFB%"    REAL,
    "HR/FB"    REAL,
    "IFH%"     REAL,
    "BUH%"     REAL,
    Starting   REAL,
    "Start-IP" REAL,
    Relieving  REAL,
    "Relief-IP" REAL,
    RAR        REAL,
    WAR        REAL,
    Dollars    TEXT,
    tERA       REAL,
    xFIP       REAL,
    WPA        REAL,
    "-WPA"     REAL,
    "+WPA"     REAL,
    RE24       REAL,
    REW        REAL,
    pLI        REAL,
    inLI       REAL,
    gmLI       REAL,
    exLI       REAL,
    Pulls      INTEGER,
    "WPA/LI"   REAL,
    Clutch     REAL
    -- (Add all remaining pitching_stats columns similarly)
);

-- ======================================================
-- Table for amateur draft (team-based)
-- ======================================================
DROP TABLE IF EXISTS amateur_draft_by_team;
CREATE TABLE amateur_draft_by_team (
    OvPck          INTEGER,
    Tm             TEXT,
    Signed         TEXT,
    Bonus          TEXT,
    Name           TEXT,
    Pos            TEXT,
    WAR            REAL,
    G              REAL,
    AB             REAL,
    HR             REAL,
    BA             REAL,
    OPS            REAL,
    "G.1"          REAL,
    W              REAL,
    L              REAL,
    ERA            REAL,
    WHIP           REAL,
    SV             REAL,
    Type           TEXT,
    "Drafted Out of" TEXT
);

-- ======================================================
-- Table for team game logs (batting logs)
-- ======================================================
DROP TABLE IF EXISTS team_game_logs_batting;
CREATE TABLE team_game_logs_batting (
    Game         INTEGER,
    Date         TEXT,
    Home         BOOLEAN,
    Opp          TEXT,
    Rslt         TEXT,
    PA           INTEGER,
    AB           INTEGER,
    R            INTEGER,
    H            INTEGER,
    "2B"         INTEGER,
    "3B"         INTEGER,
    HR           INTEGER,
    RBI          INTEGER,
    BB           INTEGER,
    IBB          INTEGER,
    SO           INTEGER,
    HBP          INTEGER,
    SH           INTEGER,
    SF           INTEGER,
    ROE          INTEGER,
    GDP          INTEGER,
    SB           INTEGER,
    CS           INTEGER,
    BA           REAL,
    OBP          REAL,
    SLG          REAL,
    OPS          REAL,
    LOB          INTEGER,
    NumPlayers   INTEGER,
    Thr          TEXT,
    OppStart     TEXT
);

-- ======================================================
-- Table for team game logs (pitching logs)
-- ======================================================
DROP TABLE IF EXISTS team_game_logs_pitching;
CREATE TABLE team_game_logs_pitching (
    Game          INTEGER,
    Date          TEXT,
    Home          BOOLEAN,
    Opp           TEXT,
    Rslt          TEXT,
    IP            REAL,
    H             INTEGER,
    R             INTEGER,
    ER            INTEGER,
    UER           INTEGER,
    BB            INTEGER,
    SO            INTEGER,
    HR            INTEGER,
    HBP           INTEGER,
    ERA           REAL,
    BF            INTEGER,
    Pit           INTEGER,
    Str           INTEGER,
    IR            REAL,
    "IS"            REAL,
    SB            INTEGER,
    CS            INTEGER,
    AB            INTEGER,
    "2B"          INTEGER,
    "3B"          INTEGER,
    IBB           INTEGER,
    SH            INTEGER,
    SF            INTEGER,
    ROE           INTEGER,
    GDP           INTEGER,
    NumPlayers    INTEGER,
    Umpire        TEXT,
    PitchersUsed  TEXT
);
